version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: odcapi
      POSTGRES_PASSWORD: odcapi
      POSTGRES_DB: odcadmin
    ports:
      - 6000:5432
  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
      args:
        API_PORT: 4321
    environment:
      DATABASE_URL: postgres://odcapi:odcapi@postgres:5432/odcadmin
      RUST_LOG: info
      API_PREFIX: ""
    ports:
      - 6001:4321
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      args:
        API_ROOT: http://localhost:6001
    ports:
      - 6002:5000
