on:
  push:
    paths-ignore:
      - ".vscode/**"
      - "docs/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "frontend/.gitignore"
      - "frontend/README.md"
      - "frontend/.vscode/**"
      - "backend/.gitignore"
      - "backend/README.md"
      - "backend/.vscode/**"
      - "backend/backup-json/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/coverage.yml"
      - ".github/workflows/fullstack.yml"

name: Docker

jobs:
  Docker:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
